"""add scheduled_at column

Revision ID: 4be03487e61e
Revises: 7812564d30e8
Create Date: 2026-06-29 08:34:07.084065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4be03487e61e'
down_revision: Union[str, None] = '7812564d30e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'scheduled_at')
    # ### end Alembic commands ###
