"""add lease columns

Revision ID: 7812564d30e8
Revises: 1a2ed4f42d3d
Create Date: 2026-06-29 06:22:19.356239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7812564d30e8'
down_revision: Union[str, None] = '1a2ed4f42d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('worker_id', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'lease_expires_at')
    op.drop_column('tasks', 'worker_id')
    # ### end Alembic commands ###
