"""add task dependencies table

Revision ID: 86e1b17da262
Revises: 4be03487e61e
Create Date: 2026-06-29 09:40:41.430065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86e1b17da262'
down_revision: Union[str, None] = '4be03487e61e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_dependencies',
    sa.Column('parent_task_id', sa.Uuid(), nullable=False),
    sa.Column('child_task_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['child_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_task_id', 'child_task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_dependencies')
    # ### end Alembic commands ###
