"""create task events table

Revision ID: bc23f9124e13
Revises: 86e1b17da262
Create Date: 2026-06-29 12:19:13.969355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc23f9124e13'
down_revision: Union[str, None] = '86e1b17da262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.Enum('TASK_CREATED', 'TASK_ENQUEUED', 'TASK_STARTED', 'TASK_COMPLETED', 'TASK_FAILED', 'TASK_BLOCKED', 'TASK_UNBLOCKED', 'TASK_SCHEDULED', 'TASK_PROMOTED', 'LEASE_ACQUIRED', 'LEASE_EXPIRED', 'TASK_RECOVERED', 'RETRY_SCHEDULED', 'DLQ_PUSHED', name='taskeventtype', native_enum=False), nullable=False),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_events')
    # ### end Alembic commands ###
